_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 40
                - 41
                - 55
            "2":
                - 1
                - 40
                - 41
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.13.1
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
batch_size:
    value: 32
beta1:
    value: 0.8192840251160546
beta2:
    value: 0.9974607872817998
beta3:
    value: 0.4668611763350746
dataset:
    value: IMDB
dataset_size:
    value: small
embed_dim:
    value: 384
epochs:
    value: 3
eps:
    value: 6.874371847643469e-08
eta:
    value: 0.005927246005129253
hidden_dim:
    value: 256
lr_cutoff:
    value: 9
max_seq_len:
    value: 128
model:
    value: MLPModel
normgrad:
    value: true
power:
    value: 1
weight_decay:
    value: 0.00950919816498432
