wandb_version: 1

adam_beta1:
  value: 0.9
adam_beta2:
  value: 0.999
adam_eps:
  value: 1.0e-08
adam_lr:
  value: 0.06345455126425728
adam_weight_decay:
  value: 1.0e-05
batch_size:
  value: 64
dataset_size:
  value: full
entropy_coef:
  value: 0.0167252734500699
epochs:
  value: 100
gamma:
  value: 0.99
hidden_dim:
  value: 256
optimizer_name:
  value: ADAM
