_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 128
beta_max:
    value: 0.02
beta_min:
    value: 0.0001
beta1:
    value: 0.9
beta2:
    value: 0.999
device:
    value: cuda
epochs:
    value: 50
eps:
    value: 1e-08
lr:
    value: 0.0001386879245014999
num_timesteps:
    value: 400
optimizer:
    value: ADAM
sample_every:
    value: 5
seed:
    value: 42
unet_base_channels:
    value: 96
unet_time_embed_dim:
    value: 128
use_attention:
    value: true
weight_decay:
    value: 1e-05
