_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 40
                - 41
                - 55
            "2":
                - 1
                - 40
                - 41
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.13.1
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
batch_size:
    value: 32
beta1:
    value: 0.971670153666389
beta2:
    value: 0.9908918021951538
beta3:
    value: 0.6242743354639132
dataset:
    value: WikiText2
dataset_size:
    value: small
embed_dim:
    value: 128
epochs:
    value: 3
eps:
    value: 8.125301177890105e-08
eta:
    value: 0.009003847152310628
hidden_dim:
    value: 768
lr_cutoff:
    value: 13
max_seq_len:
    value: 256
model:
    value: TransformerModel
normgrad:
    value: false
power:
    value: 1
weight_decay:
    value: 0.0019481640658357924
