wandb_version: 1

batch_size:
  value: 32
beta1:
  value: 0.9
beta2:
  value: 0.999
beta3:
  value: 2.4410045737992396
dataset_size:
  value: full
embed_dim:
  value: 128
epochs:
  value: 100
eps:
  value: 1.0e-08
eta:
  value: 1.1968980381739472e-05
hidden_dim:
  value: 256
lr_cutoff:
  value: 15
lr_eta_min:
  value: 1.0e-05
lr_scheduler_type:
  value: WarmupCosineAnnealing
lr_warmup_epochs:
  value: 5
lr_warmup_factor:
  value: 0.1
max_seq_len:
  value: 64
normgrad:
  value: false
optimizer_name:
  value: VADAM
power:
  value: 2
seed:
  value: 0
weight_decay:
  value: 1.0e-05
