_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.11
            "8":
                - 5
            "10":
                - 20
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 128
criterion:
    value: CrossEntropyLoss
dataset:
    value: CIFAR10
device:
    value: cuda
epochs:
    value: 20
learning_rate:
    value: 0.01
model_class:
    value: SimpleCNN
num_power_iterations:
    value: 10
optimizer:
    value: VADAM
