_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 40
                - 41
                - 55
            "2":
                - 1
                - 40
                - 41
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.13.1
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
batch_size:
    value: 64
beta1:
    value: 0.8890074302429876
beta2:
    value: 0.9903939126650751
beta3:
    value: 0.5199106501069811
dataset:
    value: WikiText2
dataset_size:
    value: small
embed_dim:
    value: 384
epochs:
    value: 3
eps:
    value: 4.561754206542692e-09
eta:
    value: 0.0010519937258192803
hidden_dim:
    value: 1024
lr_cutoff:
    value: 26
max_seq_len:
    value: 64
model:
    value: TransformerModel
normgrad:
    value: false
power:
    value: 1
weight_decay:
    value: 0.009640231281128791
