wandb_version: 1

batch_size:
  value: 64
beta1:
  value: 0.9
beta2:
  value: 0.999
beta3:
  value: 0.6300949481819171
dataset_size:
  value: full
entropy_coef:
  value: 0.03281935226565355
epochs:
  value: 100
eps:
  value: 1.0e-08
eta:
  value: 0.00013200487065741752
gamma:
  value: 0.99
hidden_dim:
  value: 128
lr_cutoff:
  value: 22
normgrad:
  value: true
optimizer_name:
  value: VADAM
power:
  value: 2
weight_decay:
  value: 1.0e-05
