wandb_version: 1

batch_size:
  value: 64
beta1:
  value: 0.9
beta2:
  value: 0.999
beta3:
  value: 0.5008082913540445
dataset_size:
  value: full
entropy_coef:
  value: 0.022532084767881815
epochs:
  value: 100
eps:
  value: 1.0e-08
eta:
  value: 0.023533819597316836
gamma:
  value: 0.99
hidden_dim:
  value: 128
lr_cutoff:
  value: 8
normgrad:
  value: false
optimizer_name:
  value: VADAM
power:
  value: 2
weight_decay:
  value: 1.0e-05
