wandb_version: 1

batch_size:
  value: 64
beta1:
  value: 0.9
beta2:
  value: 0.999
beta3:
  value: 1.5447088612977706
dataset_size:
  value: full
entropy_coef:
  value: 0.005022882041777572
epochs:
  value: 100
eps:
  value: 1.0e-08
eta:
  value: 9.11549007875049e-05
gamma:
  value: 0.99
hidden_dim:
  value: 128
lr_cutoff:
  value: 29
normgrad:
  value: false
optimizer_name:
  value: VADAM
power:
  value: 2
weight_decay:
  value: 1.0e-05
