wandb_version: 1

batch_size:
  value: 64
beta1:
  value: 0.9
beta2:
  value: 0.999
beta3:
  value: 1.3987486301146586
dataset_size:
  value: full
entropy_coef:
  value: 0.00926026327872757
epochs:
  value: 100
eps:
  value: 1.0e-08
eta:
  value: 0.0009848971730765802
gamma:
  value: 0.99
hidden_dim:
  value: 256
lr_cutoff:
  value: 12
normgrad:
  value: false
optimizer_name:
  value: VADAM
power:
  value: 2
weight_decay:
  value: 1.0e-05
