_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.17
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_eps:
    value: 1e-08
adam_lr:
    value: 0.00029611869116310635
adam_weight_decay:
    value: 1e-05
batch_size:
    value: 32
dataset_size:
    value: full
embed_dim:
    value: 128
epochs:
    value: 100
hidden_dim:
    value: 256
lr_eta_min:
    value: 1e-05
lr_scheduler_type:
    value: WarmupCosineAnnealing
lr_warmup_epochs:
    value: 5
lr_warmup_factor:
    value: 0.1
max_seq_len:
    value: 64
optimizer_name:
    value: ADAM
seed:
    value: 0
