wandb_version: 1

adam_beta1:
  value: 0.9
adam_beta2:
  value: 0.999
adam_eps:
  value: 1.0e-08
adam_lr:
  value: 2.3425385884215142e-05
adam_weight_decay:
  value: 1.0e-05
batch_size:
  value: 64
dataset_size:
  value: full
entropy_coef:
  value: 0.0010386722929718352
epochs:
  value: 100
gamma:
  value: 0.99
hidden_dim:
  value: 128
optimizer_name:
  value: ADAM
