wandb_version: 1

batch_size:
  value: 1024
dataset:
  value: CIFAR10
dataset_size:
  value: full
embed_dim:
  value: 300
epochs:
  value: 100
hidden_dim:
  value: 512
lr_eta_min:
  value: 1.0e-05
lr_scheduler_type:
  value: WarmupCosineAnnealing
lr_warmup_epochs:
  value: 5
lr_warmup_factor:
  value: 0.1
max_seq_len:
  value: 256
model:
  value: DeeperCNN
optimizer_name:
  value: RMSPROP
rmsprop_alpha:
  value: 0.99
rmsprop_eps:
  value: 1.0e-08
rmsprop_lr:
  value: 1.729291729900993e-05
rmsprop_momentum:
  value: 0.2
rmsprop_weight_decay:
  value: 1.0e-05
