_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.17
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 32
beta1:
    value: 0.9
beta2:
    value: 0.999
beta3:
    value: 4.651340440288588
dataset_size:
    value: full
embed_dim:
    value: 128
epochs:
    value: 100
eps:
    value: 1e-08
eta:
    value: 0.0002562362675590736
hidden_dim:
    value: 256
lr_cutoff:
    value: 14
lr_eta_min:
    value: 1e-05
lr_scheduler_type:
    value: WarmupCosineAnnealing
lr_warmup_epochs:
    value: 5
lr_warmup_factor:
    value: 0.1
max_seq_len:
    value: 64
normgrad:
    value: false
optimizer_name:
    value: VADAM
power:
    value: 2
seed:
    value: 0
weight_decay:
    value: 1e-05
