_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 40
                - 41
                - 55
            "2":
                - 1
                - 40
                - 41
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.13.1
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
batch_size:
    value: 32
beta1:
    value: 0.9625072921112864
beta2:
    value: 0.9954615923639768
beta3:
    value: 1.3735564677905616
dataset:
    value: IMDB
dataset_size:
    value: small
embed_dim:
    value: 512
epochs:
    value: 3
eps:
    value: 9.894313985515273e-08
eta:
    value: 0.0001708359844514079
hidden_dim:
    value: 768
lr_cutoff:
    value: 21
max_seq_len:
    value: 128
model:
    value: MLPModel
normgrad:
    value: true
power:
    value: 2
weight_decay:
    value: 0.00010566979225230533
