wandb_version: 1

batch_size:
  value: 64
beta1:
  value: 0.9
beta2:
  value: 0.999
beta3:
  value: 1.2348117643262244
dataset_size:
  value: full
entropy_coef:
  value: 0.04369696135016462
epochs:
  value: 100
eps:
  value: 1.0e-08
eta:
  value: 0.005883602105303347
gamma:
  value: 0.99
hidden_dim:
  value: 128
lr_cutoff:
  value: 30
normgrad:
  value: true
optimizer_name:
  value: VADAM
power:
  value: 2
weight_decay:
  value: 1.0e-05
