wandb_version: 1

batch_size:
  value: 64
beta1:
  value: 0.9
beta2:
  value: 0.999
beta3:
  value: 1.0418605369418934
dataset_size:
  value: full
entropy_coef:
  value: 0.03622767099881982
epochs:
  value: 100
eps:
  value: 1.0e-08
eta:
  value: 0.025595357469947923
gamma:
  value: 0.99
hidden_dim:
  value: 512
lr_cutoff:
  value: 19
normgrad:
  value: true
optimizer_name:
  value: VADAM
power:
  value: 2
weight_decay:
  value: 1.0e-05
