_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 40
                - 41
                - 55
            "2":
                - 1
                - 40
                - 41
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.13.1
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
batch_size:
    value: 32
beta1:
    value: 0.9198617412202028
beta2:
    value: 0.9975481620143756
beta3:
    value: 0.34888084555139265
dataset:
    value: IMDB
dataset_size:
    value: small
embed_dim:
    value: 384
epochs:
    value: 3
eps:
    value: 5.595426857054394e-08
eta:
    value: 0.005602977696070864
hidden_dim:
    value: 256
lr_cutoff:
    value: 27
max_seq_len:
    value: 128
model:
    value: MLPModel
normgrad:
    value: true
power:
    value: 2
weight_decay:
    value: 0.003914341660486994
