wandb_version: 1

adam_beta1:
  value: 0.9
adam_beta2:
  value: 0.999
adam_eps:
  value: 1.0e-08
adam_lr:
  value: 0.0017749681270441224
adam_weight_decay:
  value: 1.0e-05
batch_size:
  value: 1024
dataset:
  value: CIFAR10
dataset_size:
  value: full
embed_dim:
  value: 300
epochs:
  value: 100
hidden_dim:
  value: 512
lr_eta_min:
  value: 1.0e-05
lr_scheduler_type:
  value: WarmupCosineAnnealing
lr_warmup_epochs:
  value: 5
lr_warmup_factor:
  value: 0.1
max_seq_len:
  value: 256
model:
  value: SimpleCNN
optimizer_name:
  value: ADAM
